repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v6.0.0
    hooks:
      - id: end-of-file-fixer
      - id: trailing-whitespace
      - id: check-yaml
        args: [--unsafe]
      - id: check-json
      - id: check-added-large-files
      - id: check-merge-conflict
      - id: check-case-conflict
      - id: detect-private-key

  - repo: https://github.com/Yelp/detect-secrets
    rev: v1.5.0
    hooks:
      - id: detect-secrets
        args: ['--baseline', '.secrets.baseline']
        exclude: pnpm-lock.yaml

  - repo: https://github.com/tbroadley/spellchecker-cli
    rev: v6.2.0
    hooks:
      - id: spellchecker-cli
        args: ['-l', 'en-GB', '-d', '.spelling', '-f', './**/*.md']
        name: spellcheck
        language_version: 18.19.1
        types: [markdown]
        stages:
          - 'pre-commit'

  - repo: local
    hooks:
      - id: format_check
        entry: pnpm format:write
        language: system
        name: format check affected
        pass_filenames: false
        stages:
          - 'pre-commit'

      - id: linting_check
        entry: pnpm lint:affected
        language: system
        name: lint check affected
        pass_filenames: false
        stages:
          - 'pre-commit'

      - id: checkov
        entry: pnpm infra:checkov
        language: system
        name: checkov IaC linting
        pass_filenames: false
        stages:
          - 'pre-commit'
        files: ^platform/infra/

  - repo: https://github.com/semgrep/semgrep
    rev: v1.89.0
    hooks:
      - id: semgrep
        name: semgrep
        entry: bash -c 'semgrep scan $(cat .semgrep-args.txt) --error "$@"' --
        language: system
        pass_filenames: true
        verbose: false
