name: Quality Checks

on:
  workflow_call:
    inputs:
      AWS_REGION:
        description: "AWS Region to deploy to"
        type: string
      STAGE:
        description: "Development stage"
        type: string
        required: true
    secrets:
      ROLE_TO_ASSUME:
        description: "AWS deployment role to assume"
        required: true

jobs:
  qualityChecks:
    runs-on: ubuntu-latest
    timeout-minutes: 60
    permissions:
      id-token: write # Required for OIDC authentication with AWS
    env:
      STAGE: ${{ inputs.STAGE }}

    steps:
      - name: Checkout repo
        uses: actions/checkout@8e8c483db84b4bee98b60c0593521ed34d9990e8 # v6.0.1
        with:
          fetch-depth: 0 # Shallow clones should be disabled for a better relevancy of analysis

      - name: Setup node
        uses: actions/setup-node@395ad3262231945c25e8478fd5baf05154b1d79f # v6.1.0
        with:
          node-version-file: ".nvmrc"

      - name: Install dependencies
        run: |
          python3 -m pip install semgrep pre-commit checkov
          npm install -g pnpm@latest-10
          pnpm install

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@56d6a583f00f6bad6d19d91d53a7bc3b8143d0e9 # v5.1.1
        with:
          role-to-assume: ${{ secrets.ROLE_TO_ASSUME }}
          aws-region: ${{ inputs.AWS_REGION }}
          role-session-name: ${{ github.run_id }}

      - name: Run Hygiene & Security Checks
        run: SKIP=semgrep pre-commit run --all-files --show-diff-on-failure

      - name: NX - set SHAs
        uses: nrwl/nx-set-shas@3e9ad7370203c1e93d109be57f3b72eb0eb511b1 # v4.4.0

      - name: Lint
        run: pnpm run lint

      - name: Type Check
        run: pnpm run tsc

      - name: Unit Tests
        run: pnpm run test

      - name: Infrastructure as Code (IaC) Linting with checkov
        run: pnpm run checkov

      - name: Run semgrep checks
        run: semgrep scan $(cat semgrep-args.txt) --error
